name: Angular CI/CD to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/731323559748/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@project-f8ae0caf-b55f-4954-9de.iam.gserviceaccount.com

      - name: Configure Docker
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/project-f8ae0caf-b55f-4954-9de/signal-forms/angular-starter:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push asia-southeast1-docker.pkg.dev/project-f8ae0caf-b55f-4954-9de/signal-forms/angular-starter:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy angular-starter-app \
            --image asia-southeast1-docker.pkg.dev/project-f8ae0caf-b55f-4954-9de/signal-forms/angular-starter:${{ github.sha }} \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --port 8080